node {
	stage ('Compile') {
		checkout scm
		def mvnHome = tool 'maven'
		sh "${mvnHome}/bin/mvn -f back/pom.xml clean install -DskipTests"
		stash 'working-copy'
	}

	stage ('Package') {
		checkout scm
		unstash 'working-copy'
		def mvnHome = tool 'maven'
		sh "${mvnHome}/bin/mvn -f back/pom.xml package"

	}

	stage('Deploy') {
		lsout = sh "ls back/install.sh"			
		println "${lsout}"
		sh "back/install.sh"
	}

	stage('Archive') {
			
	}
}